---

- name: Place Keystone.conf
  template:
    src: "keystone.conf.j2"
    dest: "/etc/keystone/keystone.conf"
  notify:
    - Restart Apache
    
- include: keystone_client_config.yml
  when: inventory_hostname == os_controller_primary_node