---
- name: install pip related packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-pip

- name: install python-openstackclient from pip
  pip:
    name: python-openstackclient
    state: latest