---
- name: Install & Configure Volume Service 
  hosts: cinder_all
  pre_tasks:
    - name: Create DB for cinder
      mysql_db:
        login_user: root
        login_host: "{{ mysql_server_address }}"
        login_password: "{{ mariadb_root_password }}"
        name: "{{ cinder_database_name }}"
        state: present
      when: inventory_hostname == os_controller_primary_node
    - name: Grant access to cinder user
      mysql_user:
        login_user: root
        login_host: "{{ mysql_server_address }}"
        login_password: "{{ mariadb_root_password }}"
        name: "{{ cinder_database_user }}"
        password: "{{ cinder_database_password }}"
        host: "{{ item }}"
        state: present
        priv: "{{ cinder_database_name }}.*:ALL"
      with_items:
        - "localhost"
        - "%"
      when: inventory_hostname == os_controller_primary_node
  roles:
    - os_cinder