---
- name: Install & Configure Glance Image Service 
  hosts: controller
  pre_tasks:
    - name: Create DB for Glance Image Service 
      mysql_db:
        login_user: root
        login_host: "{{ mysql_server_address }}"
        login_password: "{{ mariadb_root_password }}"
        name: "{{ glance_database_name }}"
        state: present
      when: inventory_hostname == os_controller_primary_node
    - name: Grant access to glance user 
      mysql_user:
        login_user: root
        login_host: "{{ mysql_server_address }}"
        login_password: "{{ mariadb_root_password }}"
        name: "{{ glance_database_user }}"
        password: "{{ glance_database_password }}"
        host: "{{ item }}"
        state: present
        priv: "{{ glance_database_name }}.*:ALL"
      with_items:
        - "localhost"
        - "%"
      when: inventory_hostname == os_controller_primary_node
  roles:
    - os_glance