---
- name: Install and Configure Keystone
  hosts: controller
  pre_tasks:
    - name: Create DB for service
      mysql_db:
        login_user: root
        login_host: "{{ mysql_server_address }}"
        login_password: "{{ mariadb_root_password }}"
        name: "{{ keystone_database_name }}"
        state: present
      when: ansible_hostname == hostvars[os_controller_primary_node]['ansible_hostname']

    - name: Grant access to keystone DB
      mysql_user:
        login_user: root
        login_host: "{{ mysql_server_address }}"
        login_password: "{{ mariadb_root_password }}"
        name: "{{ keystone_database_user }}"
        password: "{{ keystone_mysql_password }}"
        host: "{{ item }}"
        state: present
        priv: "{{ keystone_database_name }}.*:ALL"
      with_items:
        - "localhost"
        - "%"
      when: ansible_hostname == hostvars[os_controller_primary_node]['ansible_hostname']
  roles:
    - os_keystone