---
- name: Install & Configure Networking Service 
  hosts: neutron_all
  pre_tasks:
    - name: Create DB for neutron
      mysql_db:
        login_user: root
        login_host: "{{ mysql_server_address }}"
        login_password: "{{ mariadb_root_password }}"
        name: "{{ neutron_database_name }}"
        state: present
      when: inventory_hostname == os_controller_primary_node
    - name: Grant access to neutron user
      mysql_user:
        login_user: root
        login_host: "{{ mysql_server_address }}"
        login_password: "{{ mariadb_root_password }}"
        name: "{{ neutron_database_user }}"
        password: "{{ neutron_database_password }}"
        host: "{{ item }}"
        state: present
        priv: "{{ neutron_database_name }}.*:ALL"
      with_items:
        - "localhost"
        - "%"
      when: inventory_hostname == os_controller_primary_node
  roles:
    - os_neutron