---
- name: Install & Configure Compute Service 
  hosts: nova_all
  pre_tasks:
    - name: Create DB for nova-api
      mysql_db:
        login_user: root
        login_host:  "{{ mysql_server_address }}"
        login_password: "{{ mariadb_root_password }}"
        name: "{{ nova_api_database_name }}"
        state: present
      when: inventory_hostname == os_controller_primary_node
    - name: Create DB for nova
      mysql_db:
        login_user: root
        login_host:  "{{ mysql_server_address }}"
        login_password: "{{ mariadb_root_password }}"
        name: "{{ nova_database_name }}"
        state: present
      when: inventory_hostname == os_controller_primary_node
    - name: Grant access to nova user
      mysql_user:
        login_user: root
        login_host:  "{{ mysql_server_address }}"
        login_password: "{{ mariadb_root_password }}"
        name: "{{ nova_database_user }}"
        password: "{{ nova_database_password }}"
        host: "{{ item }}"
        state: present
        priv: "{{ nova_api_database_name }}.*:ALL/{{ nova_database_name }}.*:ALL"
      with_items:
        - "localhost"
        - "%"
      when: inventory_hostname == os_controller_primary_node
  roles:
    - os_nova