---
- include: glance_service_setup.yml
  when: inventory_hostname == os_controller_primary_node

- include: glance_configure.yml

- include: glance_db_setup.yml
  when: inventory_hostname == os_controller_primary_node

- include: glance_ssl.yml
  when: glance_service_proto == "https"