---
- name: restart memcached service
  service:
    name: "memcached"
    state: restarted
  register: service_restarted
  until: service_restarted|success
  retries: 5
  delay: 1

- name: restart ntp server
  service:
    name: "chrony"
    state: restarted
  register: service_restarted
  until: service_restarted|success
  retries: 5
  delay: 1

- name: restart rabbitmq-server
  service:
    name: "rabbitmq-server"
    state: "restarted"
    enabled: True
  register: service_restarted
  until: service_restarted|success
  retries: 5
  delay: 1
