---

- name: include external interface config file
  lineinfile:
    dest: "/etc/network/interfaces"
    line: "source {{ infras_network_interface_include_dir }}/*.cfg"

- name: ensure include interface config exist
  file:
    dest: "{{ infras_network_interface_include_dir }}"
    state: directory
    owner: root
    group: root

- name: place neutron provider interface config 
  template:
    src: "neutron_provider_interface.cfg.j2"
    dest: "{{ infras_network_interface_include_dir }}/neutron_provider_interface.cfg"
    owner: root
    group: root
  register: interface_config

- name: disable provider network interface 
  shell: "ifdown {{ neutron_provider_interface }}"
  ignore_errors: True
  when: interface_config|success

- name: enable provider network interface 
  shell: "ifup {{ neutron_provider_interface }}"
  when: interface_config|success
