---
- name: Gather variables for each distribution
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    -  "{{ ansible_distribution | lower }}.yml"

# - Prepare /etc/hosts
- include: infra_etc_hosts.yml

# - Prepare Provider Network
- include: infra_network.yml

# - NTP Services
- include: infra_ntp.yml

# Memcached
- include: infra_memcached.yml
  when: inventory_hostname in groups['memcached']

# - Repository + extra pkg
- include: infra_repository.yml
- include: infra_extra_packages.yml

- meta: flush_handlers