---

# SSL Options
nova_ssl_self_signed_regen: False
nova_ssl_self_signed_subject: "/C=US/ST=Texas/L=San Antonio/O=IT/CN={{ nova_api_bind_host }}"
nova_ssl_dir: "/etc/nova/ssl"
nova_ssl_cert: "{{ nova_ssl_dir }}/nova.pem"
nova_ssl_key: "{{ nova_ssl_dir }}/nova.key"

nova_api_database_name: nova_api
nova_database_name: nova

nova_database_user: nova

# Service Options
nova_service_name: nova
nova_service_type: compute
nova_service_description: "OpenStack Compute"

# System
nova_system_user: nova
nova_system_group: nova